//索引系统服务协议

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.0
// source: index.proto

package index

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//操作类型
type OpType int32

const (
	OpType_Upsert OpType = 0 //不存在则插入，存在则更新
	OpType_Update OpType = 1 //更新，但是key必须存在
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "Upsert",
		1: "Update",
	}
	OpType_value = map[string]int32{
		"Upsert": 0,
		"Update": 1,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_index_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_index_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{0}
}

//索引存储value类型
type IndexValueData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *IndexValueData) Reset() {
	*x = IndexValueData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexValueData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexValueData) ProtoMessage() {}

func (x *IndexValueData) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexValueData.ProtoReflect.Descriptor instead.
func (*IndexValueData) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{0}
}

func (x *IndexValueData) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

//Item
type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                              //唯一ID，一般对应ProductID
	SortValue        float64 `protobuf:"fixed64,2,opt,name=SortValue,proto3" json:"SortValue,omitempty"`              //打分值
	Time             int64   `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`                         //时间戳
	InvalidSortValue bool    `protobuf:"varint,4,opt,name=InvalidSortValue,proto3" json:"InvalidSortValue,omitempty"` //打分值是否无效，默认false更新
	InvalidTime      bool    `protobuf:"varint,5,opt,name=InvalidTime,proto3" json:"InvalidTime,omitempty"`           //时间戳是否无效，默认false更新
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetSortValue() float64 {
	if x != nil {
		return x.SortValue
	}
	return 0
}

func (x *Item) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Item) GetInvalidSortValue() bool {
	if x != nil {
		return x.InvalidSortValue
	}
	return false
}

func (x *Item) GetInvalidTime() bool {
	if x != nil {
		return x.InvalidTime
	}
	return false
}

//AddItem Request
type AddItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item    []*Item `protobuf:"bytes,1,rep,name=Item,proto3" json:"Item,omitempty"`                  //items
	MainKey string  `protobuf:"bytes,2,opt,name=MainKey,proto3" json:"MainKey,omitempty"`            //主key
	OpType  OpType  `protobuf:"varint,3,opt,name=OpType,proto3,enum=OpType" json:"OpType,omitempty"` //操作类型
	Version string  `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`            //版本号
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemReq) GetItem() []*Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *AddItemReq) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

func (x *AddItemReq) GetOpType() OpType {
	if x != nil {
		return x.OpType
	}
	return OpType_Upsert
}

func (x *AddItemReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

//AddItem Response
type AddItemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                //item id
	ItemCount int32  `protobuf:"varint,2,opt,name=ItemCount,proto3" json:"ItemCount,omitempty"` //item count in bucket
	Msg       string `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`              //return msg
	Ret       int32  `protobuf:"varint,4,opt,name=Ret,proto3" json:"Ret,omitempty"`             //返回值return code
}

func (x *AddItemRsp) Reset() {
	*x = AddItemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRsp) ProtoMessage() {}

func (x *AddItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRsp.ProtoReflect.Descriptor instead.
func (*AddItemRsp) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{3}
}

func (x *AddItemRsp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddItemRsp) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *AddItemRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddItemRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

//RemoveItem Request
type RemoveItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      []string `protobuf:"bytes,1,rep,name=Id,proto3" json:"Id,omitempty"`           //items id
	MainKey string   `protobuf:"bytes,2,opt,name=MainKey,proto3" json:"MainKey,omitempty"` //主key
	Version string   `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"` //版本号
}

func (x *RemoveItemReq) Reset() {
	*x = RemoveItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemReq) ProtoMessage() {}

func (x *RemoveItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemReq.ProtoReflect.Descriptor instead.
func (*RemoveItemReq) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveItemReq) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RemoveItemReq) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

func (x *RemoveItemReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

//RemoveItem Response
type RemoveItemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangeCount int32  `protobuf:"varint,1,opt,name=ChangeCount,proto3" json:"ChangeCount,omitempty"` //发生变更的个数
	ItemCount   int32  `protobuf:"varint,2,opt,name=ItemCount,proto3" json:"ItemCount,omitempty"`     //item count in bucket
	Msg         string `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`                  //return msg
	Ret         int32  `protobuf:"varint,4,opt,name=Ret,proto3" json:"Ret,omitempty"`                 //return code
}

func (x *RemoveItemRsp) Reset() {
	*x = RemoveItemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRsp) ProtoMessage() {}

func (x *RemoveItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRsp.ProtoReflect.Descriptor instead.
func (*RemoveItemRsp) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveItemRsp) GetChangeCount() int32 {
	if x != nil {
		return x.ChangeCount
	}
	return 0
}

func (x *RemoveItemRsp) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *RemoveItemRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RemoveItemRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

//ReadItems Request
type ReadItemsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MainKey     string   `protobuf:"bytes,1,opt,name=MainKey,proto3" json:"MainKey,omitempty"`         //主key
	ItemCount   int32    `protobuf:"varint,2,opt,name=ItemCount,proto3" json:"ItemCount,omitempty"`    //限制长度
	BloomFilter [][]byte `protobuf:"bytes,3,rep,name=BloomFilter,proto3" json:"BloomFilter,omitempty"` //布隆过滤器
	Version     string   `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`         //版本号
}

func (x *ReadItemsReq) Reset() {
	*x = ReadItemsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadItemsReq) ProtoMessage() {}

func (x *ReadItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadItemsReq.ProtoReflect.Descriptor instead.
func (*ReadItemsReq) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{6}
}

func (x *ReadItemsReq) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

func (x *ReadItemsReq) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *ReadItemsReq) GetBloomFilter() [][]byte {
	if x != nil {
		return x.BloomFilter
	}
	return nil
}

func (x *ReadItemsReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

//ReadItems Response
type ReadItemsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item []*Item `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"` //items
	Msg  string  `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`   //return msg
	Ret  int32   `protobuf:"varint,3,opt,name=Ret,proto3" json:"Ret,omitempty"`  //return code
}

func (x *ReadItemsRsp) Reset() {
	*x = ReadItemsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadItemsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadItemsRsp) ProtoMessage() {}

func (x *ReadItemsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadItemsRsp.ProtoReflect.Descriptor instead.
func (*ReadItemsRsp) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{7}
}

func (x *ReadItemsRsp) GetItem() []*Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ReadItemsRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReadItemsRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

//DeleteKey Request
type DeleteKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MainKey string `protobuf:"bytes,1,opt,name=MainKey,proto3" json:"MainKey,omitempty"`
}

func (x *DeleteKeyReq) Reset() {
	*x = DeleteKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyReq) ProtoMessage() {}

func (x *DeleteKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyReq.ProtoReflect.Descriptor instead.
func (*DeleteKeyReq) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteKeyReq) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

//DeleteKey Response
type DeleteKeyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //return code
}

func (x *DeleteKeyRsp) Reset() {
	*x = DeleteKeyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRsp) ProtoMessage() {}

func (x *DeleteKeyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRsp.ProtoReflect.Descriptor instead.
func (*DeleteKeyRsp) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteKeyRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

//布隆过滤器编解码存储value类型
type BloomFilterValueData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BloomFilters [][]byte `protobuf:"bytes,1,rep,name=BloomFilters,proto3" json:"BloomFilters,omitempty"`
}

func (x *BloomFilterValueData) Reset() {
	*x = BloomFilterValueData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BloomFilterValueData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloomFilterValueData) ProtoMessage() {}

func (x *BloomFilterValueData) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloomFilterValueData.ProtoReflect.Descriptor instead.
func (*BloomFilterValueData) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{10}
}

func (x *BloomFilterValueData) GetBloomFilters() [][]byte {
	if x != nil {
		return x.BloomFilters
	}
	return nil
}

//Write BloomFilter Request
type WriteBloomFilterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`   //user id
	ItemIds []string `protobuf:"bytes,2,rep,name=ItemIds,proto3" json:"ItemIds,omitempty"` //item id list
}

func (x *WriteBloomFilterReq) Reset() {
	*x = WriteBloomFilterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBloomFilterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBloomFilterReq) ProtoMessage() {}

func (x *WriteBloomFilterReq) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBloomFilterReq.ProtoReflect.Descriptor instead.
func (*WriteBloomFilterReq) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{11}
}

func (x *WriteBloomFilterReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *WriteBloomFilterReq) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

//Write BloomFilter Response
type WriteBloomFilterRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *WriteBloomFilterRsp) Reset() {
	*x = WriteBloomFilterRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBloomFilterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBloomFilterRsp) ProtoMessage() {}

func (x *WriteBloomFilterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBloomFilterRsp.ProtoReflect.Descriptor instead.
func (*WriteBloomFilterRsp) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{12}
}

func (x *WriteBloomFilterRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *WriteBloomFilterRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//Read BloomFilter Request
type ReadBloomFilterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *ReadBloomFilterReq) Reset() {
	*x = ReadBloomFilterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBloomFilterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBloomFilterReq) ProtoMessage() {}

func (x *ReadBloomFilterReq) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBloomFilterReq.ProtoReflect.Descriptor instead.
func (*ReadBloomFilterReq) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{13}
}

func (x *ReadBloomFilterReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

//Read BloomFilter Response
type ReadBloomFilterRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BloomFilters [][]byte `protobuf:"bytes,1,rep,name=BloomFilters,proto3" json:"BloomFilters,omitempty"` //布隆过滤器
	Ret          int32    `protobuf:"varint,2,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Msg          string   `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *ReadBloomFilterRsp) Reset() {
	*x = ReadBloomFilterRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBloomFilterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBloomFilterRsp) ProtoMessage() {}

func (x *ReadBloomFilterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBloomFilterRsp.ProtoReflect.Descriptor instead.
func (*ReadBloomFilterRsp) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{14}
}

func (x *ReadBloomFilterRsp) GetBloomFilters() [][]byte {
	if x != nil {
		return x.BloomFilters
	}
	return nil
}

func (x *ReadBloomFilterRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ReadBloomFilterRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_index_proto protoreflect.FileDescriptor

var file_index_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a,
	0x0e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1b, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x96, 0x01, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x53, 0x6f, 0x72, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x53, 0x6f, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x6f, 0x72, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x7c, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x06, 0x4f, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x4f, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x5e, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x73,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x52, 0x65, 0x74, 0x22, 0x53, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x73, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x49,
	0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x52,
	0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x82, 0x01,
	0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x49, 0x74, 0x65,
	0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x42, 0x6c, 0x6f,
	0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52,
	0x73, 0x70, 0x12, 0x19, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65,
	0x74, 0x22, 0x28, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x22, 0x20, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x52,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x3a, 0x0a,
	0x14, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x42, 0x6c, 0x6f,
	0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x47, 0x0a, 0x13, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x73, 0x22, 0x39, 0x0a, 0x13, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x6f, 0x6d,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x2c, 0x0a,
	0x12, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5c, 0x0a, 0x12, 0x52,
	0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x2a, 0x20, 0x0a, 0x06, 0x4f, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x01, 0x32, 0xc0, 0x02, 0x0a, 0x0c,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0b, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x0d, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x0d, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x2b, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x0d, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x40, 0x0a,
	0x10, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x14, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42,
	0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x13, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6c,
	0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_index_proto_rawDescOnce sync.Once
	file_index_proto_rawDescData = file_index_proto_rawDesc
)

func file_index_proto_rawDescGZIP() []byte {
	file_index_proto_rawDescOnce.Do(func() {
		file_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_index_proto_rawDescData)
	})
	return file_index_proto_rawDescData
}

var file_index_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_index_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_index_proto_goTypes = []interface{}{
	(OpType)(0),                  // 0: OpType
	(*IndexValueData)(nil),       // 1: IndexValueData
	(*Item)(nil),                 // 2: Item
	(*AddItemReq)(nil),           // 3: AddItemReq
	(*AddItemRsp)(nil),           // 4: AddItemRsp
	(*RemoveItemReq)(nil),        // 5: RemoveItemReq
	(*RemoveItemRsp)(nil),        // 6: RemoveItemRsp
	(*ReadItemsReq)(nil),         // 7: ReadItemsReq
	(*ReadItemsRsp)(nil),         // 8: ReadItemsRsp
	(*DeleteKeyReq)(nil),         // 9: DeleteKeyReq
	(*DeleteKeyRsp)(nil),         // 10: DeleteKeyRsp
	(*BloomFilterValueData)(nil), // 11: BloomFilterValueData
	(*WriteBloomFilterReq)(nil),  // 12: WriteBloomFilterReq
	(*WriteBloomFilterRsp)(nil),  // 13: WriteBloomFilterRsp
	(*ReadBloomFilterReq)(nil),   // 14: ReadBloomFilterReq
	(*ReadBloomFilterRsp)(nil),   // 15: ReadBloomFilterRsp
}
var file_index_proto_depIdxs = []int32{
	2,  // 0: IndexValueData.Items:type_name -> Item
	2,  // 1: AddItemReq.Item:type_name -> Item
	0,  // 2: AddItemReq.OpType:type_name -> OpType
	2,  // 3: ReadItemsRsp.item:type_name -> Item
	3,  // 4: IndexService.AddItem:input_type -> AddItemReq
	5,  // 5: IndexService.RemoveItem:input_type -> RemoveItemReq
	7,  // 6: IndexService.ReadItems:input_type -> ReadItemsReq
	9,  // 7: IndexService.DeleteKey:input_type -> DeleteKeyReq
	12, // 8: IndexService.WriteBloomFilter:input_type -> WriteBloomFilterReq
	14, // 9: IndexService.ReadBloomFilter:input_type -> ReadBloomFilterReq
	4,  // 10: IndexService.AddItem:output_type -> AddItemRsp
	6,  // 11: IndexService.RemoveItem:output_type -> RemoveItemRsp
	8,  // 12: IndexService.ReadItems:output_type -> ReadItemsRsp
	10, // 13: IndexService.DeleteKey:output_type -> DeleteKeyRsp
	13, // 14: IndexService.WriteBloomFilter:output_type -> WriteBloomFilterRsp
	15, // 15: IndexService.ReadBloomFilter:output_type -> ReadBloomFilterRsp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_index_proto_init() }
func file_index_proto_init() {
	if File_index_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexValueData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveItemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadItemsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadItemsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BloomFilterValueData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteBloomFilterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteBloomFilterRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBloomFilterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBloomFilterRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_index_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_index_proto_goTypes,
		DependencyIndexes: file_index_proto_depIdxs,
		EnumInfos:         file_index_proto_enumTypes,
		MessageInfos:      file_index_proto_msgTypes,
	}.Build()
	File_index_proto = out.File
	file_index_proto_rawDesc = nil
	file_index_proto_goTypes = nil
	file_index_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IndexServiceClient is the client API for IndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IndexServiceClient interface {
	//add item 添加Item，同个主key可一次添加多个Item
	AddItem(ctx context.Context, in *AddItemReq, opts ...grpc.CallOption) (*AddItemRsp, error)
	//delete item 删除Item，同个主Key可一次删除多个Item
	RemoveItem(ctx context.Context, in *RemoveItemReq, opts ...grpc.CallOption) (*RemoveItemRsp, error)
	//read items 读取Item列表
	ReadItems(ctx context.Context, in *ReadItemsReq, opts ...grpc.CallOption) (*ReadItemsRsp, error)
	//delete MainKey 删除主Key
	DeleteKey(ctx context.Context, in *DeleteKeyReq, opts ...grpc.CallOption) (*DeleteKeyRsp, error)
	//布隆过滤器：写入
	WriteBloomFilter(ctx context.Context, in *WriteBloomFilterReq, opts ...grpc.CallOption) (*WriteBloomFilterRsp, error)
	//布隆过滤器：读出
	ReadBloomFilter(ctx context.Context, in *ReadBloomFilterReq, opts ...grpc.CallOption) (*ReadBloomFilterRsp, error)
}

type indexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexServiceClient(cc grpc.ClientConnInterface) IndexServiceClient {
	return &indexServiceClient{cc}
}

func (c *indexServiceClient) AddItem(ctx context.Context, in *AddItemReq, opts ...grpc.CallOption) (*AddItemRsp, error) {
	out := new(AddItemRsp)
	err := c.cc.Invoke(ctx, "/IndexService/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) RemoveItem(ctx context.Context, in *RemoveItemReq, opts ...grpc.CallOption) (*RemoveItemRsp, error) {
	out := new(RemoveItemRsp)
	err := c.cc.Invoke(ctx, "/IndexService/RemoveItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) ReadItems(ctx context.Context, in *ReadItemsReq, opts ...grpc.CallOption) (*ReadItemsRsp, error) {
	out := new(ReadItemsRsp)
	err := c.cc.Invoke(ctx, "/IndexService/ReadItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) DeleteKey(ctx context.Context, in *DeleteKeyReq, opts ...grpc.CallOption) (*DeleteKeyRsp, error) {
	out := new(DeleteKeyRsp)
	err := c.cc.Invoke(ctx, "/IndexService/DeleteKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) WriteBloomFilter(ctx context.Context, in *WriteBloomFilterReq, opts ...grpc.CallOption) (*WriteBloomFilterRsp, error) {
	out := new(WriteBloomFilterRsp)
	err := c.cc.Invoke(ctx, "/IndexService/WriteBloomFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) ReadBloomFilter(ctx context.Context, in *ReadBloomFilterReq, opts ...grpc.CallOption) (*ReadBloomFilterRsp, error) {
	out := new(ReadBloomFilterRsp)
	err := c.cc.Invoke(ctx, "/IndexService/ReadBloomFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServiceServer is the server API for IndexService service.
type IndexServiceServer interface {
	//add item 添加Item，同个主key可一次添加多个Item
	AddItem(context.Context, *AddItemReq) (*AddItemRsp, error)
	//delete item 删除Item，同个主Key可一次删除多个Item
	RemoveItem(context.Context, *RemoveItemReq) (*RemoveItemRsp, error)
	//read items 读取Item列表
	ReadItems(context.Context, *ReadItemsReq) (*ReadItemsRsp, error)
	//delete MainKey 删除主Key
	DeleteKey(context.Context, *DeleteKeyReq) (*DeleteKeyRsp, error)
	//布隆过滤器：写入
	WriteBloomFilter(context.Context, *WriteBloomFilterReq) (*WriteBloomFilterRsp, error)
	//布隆过滤器：读出
	ReadBloomFilter(context.Context, *ReadBloomFilterReq) (*ReadBloomFilterRsp, error)
}

// UnimplementedIndexServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIndexServiceServer struct {
}

func (*UnimplementedIndexServiceServer) AddItem(context.Context, *AddItemReq) (*AddItemRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItem not implemented")
}
func (*UnimplementedIndexServiceServer) RemoveItem(context.Context, *RemoveItemReq) (*RemoveItemRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveItem not implemented")
}
func (*UnimplementedIndexServiceServer) ReadItems(context.Context, *ReadItemsReq) (*ReadItemsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadItems not implemented")
}
func (*UnimplementedIndexServiceServer) DeleteKey(context.Context, *DeleteKeyReq) (*DeleteKeyRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKey not implemented")
}
func (*UnimplementedIndexServiceServer) WriteBloomFilter(context.Context, *WriteBloomFilterReq) (*WriteBloomFilterRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteBloomFilter not implemented")
}
func (*UnimplementedIndexServiceServer) ReadBloomFilter(context.Context, *ReadBloomFilterReq) (*ReadBloomFilterRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBloomFilter not implemented")
}

func RegisterIndexServiceServer(s *grpc.Server, srv IndexServiceServer) {
	s.RegisterService(&_IndexService_serviceDesc, srv)
}

func _IndexService_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IndexService/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).AddItem(ctx, req.(*AddItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_RemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).RemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IndexService/RemoveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).RemoveItem(ctx, req.(*RemoveItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_ReadItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).ReadItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IndexService/ReadItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).ReadItems(ctx, req.(*ReadItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IndexService/DeleteKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).DeleteKey(ctx, req.(*DeleteKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_WriteBloomFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteBloomFilterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).WriteBloomFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IndexService/WriteBloomFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).WriteBloomFilter(ctx, req.(*WriteBloomFilterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_ReadBloomFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBloomFilterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).ReadBloomFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IndexService/ReadBloomFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).ReadBloomFilter(ctx, req.(*ReadBloomFilterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IndexService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IndexService",
	HandlerType: (*IndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItem",
			Handler:    _IndexService_AddItem_Handler,
		},
		{
			MethodName: "RemoveItem",
			Handler:    _IndexService_RemoveItem_Handler,
		},
		{
			MethodName: "ReadItems",
			Handler:    _IndexService_ReadItems_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _IndexService_DeleteKey_Handler,
		},
		{
			MethodName: "WriteBloomFilter",
			Handler:    _IndexService_WriteBloomFilter_Handler,
		},
		{
			MethodName: "ReadBloomFilter",
			Handler:    _IndexService_ReadBloomFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "index.proto",
}
