//召回服务协议

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.0
// source: recall.proto

package recall

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      uint64            `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`                                                                                          //用户Id
	FeedID      string            `protobuf:"bytes,2,opt,name=FeedID,proto3" json:"FeedID,omitempty"`                                                                                           //FeedID
	ItemCount   int32             `protobuf:"varint,3,opt,name=ItemCount,proto3" json:"ItemCount,omitempty"`                                                                                    //召回数量
	TimeOutInMS int32             `protobuf:"varint,4,opt,name=TimeOutInMS,proto3" json:"TimeOutInMS,omitempty"`                                                                                //召回超时时间，必须在该时间内返回（无论是否有结果）
	Extends     map[string]string `protobuf:"bytes,5,rep,name=Extends,proto3" json:"Extends,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //扩展参数
}

func (x *RecallReq) Reset() {
	*x = RecallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallReq) ProtoMessage() {}

func (x *RecallReq) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallReq.ProtoReflect.Descriptor instead.
func (*RecallReq) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{0}
}

func (x *RecallReq) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RecallReq) GetFeedID() string {
	if x != nil {
		return x.FeedID
	}
	return ""
}

func (x *RecallReq) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *RecallReq) GetTimeOutInMS() int32 {
	if x != nil {
		return x.TimeOutInMS
	}
	return 0
}

func (x *RecallReq) GetExtends() map[string]string {
	if x != nil {
		return x.Extends
	}
	return nil
}

type RecallRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecallResults []*RecallItem `protobuf:"bytes,1,rep,name=RecallResults,proto3" json:"RecallResults,omitempty"` //返回Items列表
}

func (x *RecallRsp) Reset() {
	*x = RecallRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecallRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRsp) ProtoMessage() {}

func (x *RecallRsp) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRsp.ProtoReflect.Descriptor instead.
func (*RecallRsp) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{1}
}

func (x *RecallRsp) GetRecallResults() []*RecallItem {
	if x != nil {
		return x.RecallResults
	}
	return nil
}

type RecallItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                                                                                                   //item id
	Score   float64           `protobuf:"fixed64,2,opt,name=Score,proto3" json:"Score,omitempty"`                                                                                           //打分值
	Extends map[string]string `protobuf:"bytes,3,rep,name=Extends,proto3" json:"Extends,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //扩展参数
}

func (x *RecallItem) Reset() {
	*x = RecallItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecallItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallItem) ProtoMessage() {}

func (x *RecallItem) ProtoReflect() protoreflect.Message {
	mi := &file_recall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallItem.ProtoReflect.Descriptor instead.
func (*RecallItem) Descriptor() ([]byte, []int) {
	return file_recall_proto_rawDescGZIP(), []int{2}
}

func (x *RecallItem) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RecallItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecallItem) GetExtends() map[string]string {
	if x != nil {
		return x.Extends
	}
	return nil
}

var File_recall_proto protoreflect.FileDescriptor

var file_recall_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea,
	0x01, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x65, 0x65, 0x64, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x65, 0x65, 0x64, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x69,
	0x6d, 0x65, 0x4f, 0x75, 0x74, 0x49, 0x6e, 0x4d, 0x53, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x49, 0x6e, 0x4d, 0x53, 0x12, 0x31, 0x0a, 0x07,
	0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x1a,
	0x3a, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3e, 0x0a, 0x09, 0x52,
	0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0d, 0x52, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x0a,
	0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x32, 0x0a, 0x07, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x45, 0x78, 0x74,
	0x65, 0x6e, 0x64, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x32, 0x33, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x22, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x12, 0x0a, 0x2e, 0x52, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c,
	0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x72, 0x65, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recall_proto_rawDescOnce sync.Once
	file_recall_proto_rawDescData = file_recall_proto_rawDesc
)

func file_recall_proto_rawDescGZIP() []byte {
	file_recall_proto_rawDescOnce.Do(func() {
		file_recall_proto_rawDescData = protoimpl.X.CompressGZIP(file_recall_proto_rawDescData)
	})
	return file_recall_proto_rawDescData
}

var file_recall_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_recall_proto_goTypes = []interface{}{
	(*RecallReq)(nil),  // 0: RecallReq
	(*RecallRsp)(nil),  // 1: RecallRsp
	(*RecallItem)(nil), // 2: RecallItem
	nil,                // 3: RecallReq.ExtendsEntry
	nil,                // 4: RecallItem.ExtendsEntry
}
var file_recall_proto_depIdxs = []int32{
	3, // 0: RecallReq.Extends:type_name -> RecallReq.ExtendsEntry
	2, // 1: RecallRsp.RecallResults:type_name -> RecallItem
	4, // 2: RecallItem.Extends:type_name -> RecallItem.ExtendsEntry
	0, // 3: RecallService.Recall:input_type -> RecallReq
	1, // 4: RecallService.Recall:output_type -> RecallRsp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_recall_proto_init() }
func file_recall_proto_init() {
	if File_recall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecallRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecallItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recall_proto_goTypes,
		DependencyIndexes: file_recall_proto_depIdxs,
		MessageInfos:      file_recall_proto_msgTypes,
	}.Build()
	File_recall_proto = out.File
	file_recall_proto_rawDesc = nil
	file_recall_proto_goTypes = nil
	file_recall_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RecallServiceClient is the client API for RecallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecallServiceClient interface {
	Recall(ctx context.Context, in *RecallReq, opts ...grpc.CallOption) (*RecallRsp, error)
}

type recallServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecallServiceClient(cc grpc.ClientConnInterface) RecallServiceClient {
	return &recallServiceClient{cc}
}

func (c *recallServiceClient) Recall(ctx context.Context, in *RecallReq, opts ...grpc.CallOption) (*RecallRsp, error) {
	out := new(RecallRsp)
	err := c.cc.Invoke(ctx, "/RecallService/Recall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecallServiceServer is the server API for RecallService service.
type RecallServiceServer interface {
	Recall(context.Context, *RecallReq) (*RecallRsp, error)
}

// UnimplementedRecallServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRecallServiceServer struct {
}

func (*UnimplementedRecallServiceServer) Recall(context.Context, *RecallReq) (*RecallRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recall not implemented")
}

func RegisterRecallServiceServer(s *grpc.Server, srv RecallServiceServer) {
	s.RegisterService(&_RecallService_serviceDesc, srv)
}

func _RecallService_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecallServiceServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecallService/Recall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecallServiceServer).Recall(ctx, req.(*RecallReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecallService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RecallService",
	HandlerType: (*RecallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recall",
			Handler:    _RecallService_Recall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recall.proto",
}
